//HintName: CustomClass.cs
// <auto-generated />
#nullable enable

partial struct CustomClass : System.IEquatable<CustomClass>, SpacetimeDB.BSATN.IStructuralReadWrite
{
    public void ReadFields(System.IO.BinaryReader reader)
    {
        IntField = BSATN.IntField.Read(reader);
        StringField = BSATN.StringField.Read(reader);
    }

    public void WriteFields(System.IO.BinaryWriter writer)
    {
        BSATN.IntField.Write(writer, IntField);
        BSATN.StringField.Write(writer, StringField);
    }

    public readonly partial struct BSATN : SpacetimeDB.BSATN.IReadWrite<CustomClass>
    {
        internal static readonly SpacetimeDB.BSATN.I32 IntField = new();
        internal static readonly SpacetimeDB.BSATN.String StringField = new();

        public CustomClass Read(System.IO.BinaryReader reader) =>
            SpacetimeDB.BSATN.IStructuralReadWrite.Read<CustomClass>(reader);

        public void Write(System.IO.BinaryWriter writer, CustomClass value)
        {
            value.WriteFields(writer);
        }

        public SpacetimeDB.BSATN.AlgebraicType.Ref GetAlgebraicType(
            SpacetimeDB.BSATN.ITypeRegistrar registrar
        ) =>
            registrar.RegisterType<CustomClass>(_ => new SpacetimeDB.BSATN.AlgebraicType.Product(
                new SpacetimeDB.BSATN.AggregateElement[]
                {
                    new(nameof(IntField), IntField.GetAlgebraicType(registrar)),
                    new(nameof(StringField), StringField.GetAlgebraicType(registrar))
                }
            ));

        SpacetimeDB.BSATN.AlgebraicType SpacetimeDB.BSATN.IReadWrite<CustomClass>.GetAlgebraicType(
            SpacetimeDB.BSATN.ITypeRegistrar registrar
        ) => GetAlgebraicType(registrar);
    }

    public override int GetHashCode()
    {
        return IntField.GetHashCode() ^ StringField.GetHashCode();
    }

    public override string ToString()
    {
        return $"CustomClass(IntField = {IntField}, StringField = {StringField}";
    }

    public bool Equals(CustomClass that)
    {
        return IntField.Equals(that.IntField) && StringField.Equals(that.StringField);
    }

    public override bool Equals(object? that)
    {
        if (that == null)
        {
            return false;
        }
        var that_ = that as CustomClass?;
        if (that_ == null)
        {
            return false;
        }
        return Equals(that);
    }

    public static bool operator ==(CustomClass this_, CustomClass that)
    {
        if (((object)this_) == null || ((object)that) == null)
        {
            return Object.Equals(this_, that);
        }
        return this_.Equals(that);
    }

    public static bool operator !=(CustomClass this_, CustomClass that)
    {
        return !(this_ == that);
    }
} // CustomClass
