default_server = "127.0.0.1:3000"
spacetimedb_token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiJ9.eyJoZXhfaWRlbnRpdHkiOiJjMjAwMzc5YmY1M2Q2ZmJhY2RkNGZkNmQzMDAzZTJiMjQ0ZWRjMzc0M2ZjZTkyYjRlYTUzNzU1ZGRhN2YxNmIxIiwic3ViIjoiYjIwNTIxZTUtZTg3Ny00NDA5LTg1NjktZTc3YmQ5ZTkwMTIzIiwiaXNzIjoibG9jYWxob3N0IiwiYXVkIjpbInNwYWNldGltZWRiIl0sImlhdCI6MTczNjE4MzU0NCwiZXhwIjpudWxsfQ.Eo_Qg2AXcZzWmAqg0-vrDQu-dYGKcGQ3FRv5rCCg3bhp7SVqVjYoLku_SwYWeWAjTkcMOpGAuAOov8mGIsb1Qg"

[[server_configs]]
nickname = "localhost"
host = "127.0.0.1:3000"
protocol = "http"
