default_server = "127.0.0.1:3000"
spacetimedb_token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiJ9.eyJoZXhfaWRlbnRpdHkiOiJjMjAwNTE4ODlhODY1OGU2ZDA0ZGE2NzRjYTI3MTgzMjFlN2Y3YmMyNWYxYzA0MzZkZTRjNDE3NDFlYmY3MTEzIiwic3ViIjoiZjQ0MzgwOGUtNjdhOS00N2NjLTgyMmItM2ZhZDhjZmQxOTA5IiwiaXNzIjoibG9jYWxob3N0IiwiYXVkIjpbInNwYWNldGltZWRiIl0sImlhdCI6MTczOTUzMjg5NSwiZXhwIjpudWxsfQ.Lu4553s68Ibb_EGdbamJ3EPTYaztd6tXg0jiZM6E3dhNmKYLeFrBYK7vsc0az2q_rROEtx2ZWHna3WjqF88kuA"

[[server_configs]]
nickname = "localhost"
host = "127.0.0.1:3000"
protocol = "http"
