on:
  pull_request:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull Request Number'
        required: false
        default: ''

name: Check CLI Docs

jobs:
  cli_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Find Git ref
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          PR_NUMBER="${{ github.event.inputs.pr_number || null }}"
          if test -n "${PR_NUMBER}"; then
            GIT_REF="$( gh pr view --repo clockworklabs/SpacetimeDB $PR_NUMBER --json headRefName --jq .headRefName )"
          else
            GIT_REF="${{ github.ref }}"
          fi
          echo "GIT_REF=${GIT_REF}" >>"$GITHUB_ENV"
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          ref: ${{ env.GIT_REF }}
      - uses: dsherret/rust-toolchain-file@v1
      - uses: actions/setup-dotnet@v4
        with:
          global-json-file: modules/global.json
      - name: Checkout docs
        uses: actions/checkout@v4
        with:
          repository: clockworklabs/spacetime-docs
          ref: master
          path: spacetime-docs
      - name: Check for docs change
        run: |
          cargo run --features markdown-docs -p spacetimedb-cli > spacetime-docs/docs/cli-reference.md
          cd spacetime-docs
          if ! git diff-index --quiet HEAD; then
            echo "It looks like the CLI docs have changed"
            git diff
            exit 1
          fi
